[tool.poetry]
name = "pyfahrplan"
version = "1.0.0"
description = ""
authors = ["Sascha <saschalalala@github.com>"]

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.0"
requests = "^2.22.0"
requests_cache = "^0.5.2"
tabulate = "^0.8.7"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
